ECommMarket.App/Controllers/PaymentController.cs
using EcommMarket.Application.Interfaces;
using EcommMarket.Application.Dto;
using ECommMarket.App.Models;
using ECommMarket.Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace ECommMarket.App.Controllers;

[Route("Order")]
public class PaymentController : Controller
{
    private readonly IMemoryCache memoryCache;
    private readonly IProductService productService;
    private readonly IOrderService orderService;
    public PaymentController(IOrderService orderService, IProductService productService, IMemoryCache memoryCache)
    {
        this.orderService = orderService;
        this.productService = productService;
        this.memoryCache = memoryCache;
    }

    [Route("")]
    public async Task<IActionResult> Index()
    {
        var cartIdentifier = Request.Cookies["cartIdentifier"];
        if(cartIdentifier is null)
        {
            return RedirectToAction("CartItems", "Cart");
        }

        if (memoryCache.TryGetValue(cartIdentifier, out Dictionary<int, int>? cacheValue))
        {
            List<ProductDto> products = await productService.GetAllByIdAsync(cacheValue.Keys.ToList());
            List<ProductViewModel> productsViewModel = products.Select(x => new ProductViewModel()
            {
                Description = x.Description,
                Id = x.Id,
                Price = x.Price,
                ProductName = x.ProductName,
                Quantity = cacheValue.TryGetValue(x.Id, out int quantity) ? quantity : 1,
                Photos = new()
                {
                    new() { PhotoName =  x.Photos!.FirstOrDefault()!.PhotoName, PhotoUrl = x.Photos!.FirstOrDefault()!.PhotoUrl }
                }
            }).ToList();
            ViewBag.Products = productsViewModel;

            return View("/Views/Payment/Payment.cshtml");
        }
        return RedirectToAction("CartItems", "Cart");
    }

    [Route("Add")]
    public async Task<IActionResult> AddOrder(OrderViewModel model)
    {
        var cartIdentifier = Request.Cookies["cartIdentifier"];

        if (!ModelState.IsValid) 
        {
            return View("/Views/Payment/Payment.cshtml", model);
        }

        if (memoryCache.TryGetValue(cartIdentifier, out Dictionary<int, int>? cacheValue))
        {
            List<ProductDto> products = await productService.GetAllByIdAsync(cacheValue.Keys.ToList());
            products.ForEach(x => x.Quantity = cacheValue.TryGetValue(x.Id, out int quantity) ? quantity : 1);

            var lastOrder = await orderService.GetLastOrderId();
            lastOrder++;

            var orderDto = new OrderDto()
            {
                Address = model.Address,
                City = model.City,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                PhoneNumber = model.PhoneNumber,
                TransactionId = lastOrder.ToString(),
                Products = products,
            };

            OrderDto savedOrder = await orderService.AddAsync(orderDto);
            OrderViewModel viewModel = new OrderViewModel()
            {
                Products = savedOrder.Products.Select(x => new ProductViewModel()
                {
                    Description = x.Description,
                    Id = x.Id,
                    Price = x.Price,
                    ProductName = x.ProductName,
                    Quantity = x.Quantity,
                    Photos = new()
                {
                    new() { PhotoName =  x.Photos!.FirstOrDefault()!.PhotoName, PhotoUrl = x.Photos!.FirstOrDefault()!.PhotoUrl }
                }
                }).ToList(),
                Address = savedOrder.Address,
                City = savedOrder.City,
                Email = savedOrder.Email,
                FirstName = savedOrder.FirstName,
                LastName = savedOrder.LastName,
                PhoneNumber = savedOrder.PhoneNumber,
                TransactionId = savedOrder.TransactionId,
                Timestamp = savedOrder.Timestamp,


            };
            return View("/Views/Order/OrderResult.cshtml" , viewModel);
        }
        else
        {
            return View(model);
        }
    }
}

ECommMarket.App/Views/Payment/Payment.cshtml
@model ECommMarket.App.Models.OrderViewModel
@{
    var products = ViewBag.Products as List<ProductViewModel>;
    decimal sum = 0;
    if (products is not null)
    {
        sum = products.Select(x => x.Price * x.Quantity).Sum();
    }
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/payment.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;900&display=swap">
    <title>შეკვეთა</title>
    <link rel="icon" href="/images/logo/BrandLogo.jpg">
</head>
<div class="info-container">
    <div class="left-column">
        <div class="payment-form">
        @using (Html.BeginForm("AddOrder", "Payment", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <h2>Billing and Shipping Information</h2>

            <label for="name">სახელი *</label>
            @Html.TextBoxFor(model => model.FirstName, new { id = "name" })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

            <label for="lastname">გვარი *</label>
            @Html.TextBoxFor(model => model.LastName, new { id = "name" })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

            <label for="Email">იმეილი *</label>
            @Html.TextBoxFor(model => model.Email, new { id = "email" })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

            <label for="PhoneNumber">ტელეფონის ნომერი *</label>
            @Html.TextBoxFor(model => model.PhoneNumber, new { id = "postcode", placeholder = "+995" })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            
            <label for="City">ქალაქი *</label>
            @Html.TextBoxFor(model => model.City, new { id = "address" })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })

            <label for="Address">მისამართი *</label>
            @Html.TextBoxFor(model => model.Address, new { id = "postcode", placeholder = "ქუჩის სახელი და სახლის ნომერი" })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })

            <button type="submit" class="btn-submit" >შეკვეთის განთავსება</button>            
        }
        </div>
    </div>

    <div class="right-column">
        <div class="order-summary">
            <div class="titles">
                <h2>პროდუქტები</h2>
                <h2>ფასი</h2>
            </div>
            <hr>
            @if(products is not null)
            {
                
            
                @foreach (var product in products)
                {
                    <div class="product">
                        <p>@product.ProductName x @product.Quantity</p>
                        <p>@product.Price.ToString("N0")₾</p>
                    </div>
                }
            }
            <hr>
            <div class="subtotal">
                <p>ჯამი:</p>
                <p>@sum₾</p>
            </div>
            <hr>
        </div>

        <div class="payment-methods">
            <h2>გადახდის მეთოდი</h2>
            <div class="method">
                <label>
                    <input type="radio" value name="payment-method" value="bank-transfer" checked>
                    <span>საბანკო გადარიცხვა</span>
                </label>
            </div>
        </div>

        @* <a ><button type="submit" class="btn-submit">შეკვეთის განთავსება</button></a> *@

        <p class="note">
            ბარათის გადახდის შემთხვევაში, ბარათის გადახდის მიღება ბანკის პირობებზე ხდება. გთხოვთ, გადახდაზე ყურადღება გაამახვილოთ, რადგან თანხა არ დაბრუნდება ან გადახდის ფორმას შესაბამისი თანხა აირიცხება.
        </p>
    </div>


</div>